version: "3.2"
services:
  api_web:
    build: site
    container_name: apache-api
    ports:
      - "8099:80"
    volumes:
      - ./:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database
    environment:
      PHP_EXTENSION_XDEBUG: 1

  database:
    image: mysql:5.7
    container_name: mysql-api
    environment:
      MYSQL_DATABASE: api-sdk
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-api
    depends_on:
      - database
    ports:
      - 8098:80
    environment:
      - PMA_ARBITRARY=1